# .bashrc
export TERM=xterm-256color

export MACOSX_DEPLOYMENT_TARGET=10.9
export CC=clang
export CXX=clang++ 

alias shome='cd $WORK_DIR'

alias ls='ls --color'
alias mv='mv -i'
alias rmf='/bin/rm -i'
alias cp='cp -i'
function cd() { builtin cd $1 && ls; }

function rm() {
    basename=${1:t} # file name without extension
    if [ -e "$WORK_DIR/.Trash/$basename" ]; then
        echo "File exists; $1 needs to be renamed.."
        i=1                 # initialize the counter
        shortname=${basename%.*} # file name without extension
        ext=${basename##*.}     # the file extension
        while [ -e "$WORK_DIR/.Trash/${shortname}_${basename}.${ext}" ]
        do
            ((i++))
        done

        mv $1 $WORK_DIR/.Trash/${shortname}_${i}.${ext}
        echo Move $1 to $WORK_DIR/.Trash/${shortname}_${i}.${ext}
    else
        mv $1 $WORK_DIR/.Trash/
        echo Move $1 to $WORK_DIR/.Trash/${basename}
    fi
}

alias nvim='nvim -u $CONFIG_DIR/nvim/init.lua'
alias vi='nvim'
alias vir='vi -R'
alias cls='clear && echo -en "\e[3J"'

alias bashrc_cfg='vi $CONFIG_DIR/bash/.bashrc'

#tmux
alias tmux='TERM=xterm-256color tmux'
alias tmuxs='tmux -u new -s shwan'
alias tn='tmux -u new -s '
alias tas='tmux attach -t shwan'
alias ta='tmux attach -t'

if { [ -n "$TMUX" ]; } then
    tmux source-file $CONFIG_DIR/tmux/.tmux.conf
else
    alias tmux='tmux -f $CONFIG_DIR/tmux/.tmux.conf'
fi

# git
alias gs='git status'                                                                                    
alias gl='git pull'                                                                                      
alias gp='git push'
alias ga='git add'                                                                                     
alias gal='git add .'
alias gcm='git commit -m '
alias gr='git restore --staged'

if { [ "$SHELLTYPE" = 'BASH' ]; } then
    source $CONFIG_DIR/git/git-completion.bash
fi
source $CONFIG_DIR/git/git-prompt.sh

if { [ "$SHELLTYPE" = 'BASH' ]; } then
    source $CONFIG_DIR/bash/ps1_bash.sh
else
    source $CONFIG_DIR/bash/ps1_zsh.sh
fi
