return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      highlight = { enable = true },
      indent = { enable = false },
      ensure_installed = {
        "bash",
        "lua",
        "html",
        "json",
        "yaml",
        "markdown_inline",
        "python",
        -- "c",
        -- "cpp",
        -- "java",
        --"javascript",
        -- "lua",
        -- "luadoc",
        -- "luap",
        --"markdown",
        -- "query",
        -- "regex",
        --"tsx",
        --"typescript",
        --"vim",
        -- "vimdoc",
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    },
  },
}
